# Generated by Django 3.0 on 2019-12-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtags', models.CharField(max_length=250)),
                ('retweet_count', models.IntegerField(default=0)),
                ('favorite_count', models.IntegerField(default=0)),
                ('user_name', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(verbose_name='date picked')),
            ],
        ),
    ]
